ALTER TABLE users
ADD COLUMN username VARCHAR(100) DEFAULT NULL,
ADD COLUMN status TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN verified TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN resettable TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
ADD COLUMN roles SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN registered INT(10) UNSIGNED NOT NULL,
ADD COLUMN force_logout INT(10) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE users CHANGE user_id id INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE users ADD COLUMN roles_mask INT(11) UNSIGNED NOT NULL DEFAULT 0;

UPDATE users SET verified = 1 WHERE email = 'admin@bfit.local';

UPDATE users SET role = 'admin' WHERE email = 'admin@bfit.local';

