services:
  php:
    image: php:8.3.17-apache
    container_name: phpBfit
    ports:
      - 8089:80
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mysql-burgos.alwaysdata.net
      DB_DATABASE: burgos_bfit
      DB_USER: burgos
      DB_PASSWORD: Is@bel1410
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - maildev

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
